// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvdxhehfujqfwecvapep.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2ZHhoZWhmdWpxZndlY3ZhcGVwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MjQyMTYsImV4cCI6MjA3MzEwMDIxNn0.i0Rlf7Xmx0vHQGRXvvjE4KCNyhNvYtylDqS4oVAM5Mo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});